# Generated by Django 3.2.19 on 2023-05-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='latitude',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='longitude',
            new_name='Longitude',
        ),
    ]
